CREATE DATABASE HAMBURGUERIA;

USE HAMBURGUERIA;

CREATE TABLE FORNECEDOR(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    TELEFONE INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CNPJ INT
);

CREATE TABLE TIPO_PRODUTO(
    ID_TIPO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL
);

CREATE TABLE FORMA_PAGAMENTO(
    ID_FORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(20) NOT NULL,
    TAXA DECIMAL(4,2) NOT NULL
);

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE INT NOT NULL,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE STATUS_PEDIDO(
    ID_STATUS INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL,
    PRIORIDADE INT NOT NULL
);

CREATE TABLE PRODUTO(
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(7,2) NOT NULL,
    DISPONIBILIDADE INT NOT NULL,
    IMAGEM_URL VARCHAR(100) NOT NULL,
    ID_TIPO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_PRODUTO(ID_TIPO)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA DATETIME NOT NULL,
    ID_CLIENTE INT NOT NULL,
    TOTAL DECIMAL(7,2) NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    ID_STATUS INT NOT NULL,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO),
    FOREIGN KEY(ID_STATUS) REFERENCES STATUS_PEDIDO(ID_STATUS)
);

CREATE TABLE ITEM_PEDIDO(
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    SUBTOTAL DECIMAL(7,2) NOT NULL,
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);