CREATE DATABASE HAMBURGUERIA;

USE HAMBURGUERIA;

CREATE TABLE CLIENTE (
    ID_Cliente INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Telefone INT NOT NULL,
    Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE TIPO_PRODUTO (
    ID_Tipo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Descricao VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUTO (
    ID_Produto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Preco DECIMAL(7,2) NOT NULL,
    ID_Tipo INT NOT NULL,
        FOREIGN KEY (ID_Tipo) REFERENCES TIPO_PRODUTO(ID_Tipo),
    Disponibilidade VARCHAR(20) NOT NULL,
    Imagem_URL VARCHAR(255) NOT NULL
);

CREATE TABLE FORNECEDOR (
    ID_Fornecedor INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Telefone INT NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    CNPJ INT UNIQUE
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_Forma_Pagamento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Descricao VARCHAR(255) NOT NULL,
    Taxa DECIMAL(7,2)
);

CREATE TABLE STATUS_PEDIDO (
    ID_Status INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Descricao VARCHAR(255) NOT NULL,
    Prioridade VARCHAR(20)
);

CREATE TABLE PEDIDO (
    ID_Pedido INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Data DATE NOT NULL,
    ID_Cliente INT NOT NULL,
        FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    Total DECIMAL(7,2) NOT NULL,
    ID_Forma_Pagamento INT NOT NULL,
        FOREIGN KEY (ID_Forma_Pagamento) REFERENCES FORMA_PAGAMENTO(ID_Forma_Pagamento),
    ID_Status INT NOT NULL,
        FOREIGN KEY (ID_Status) REFERENCES STATUS_PEDIDO(ID_Status)
);

CREATE TABLE ITEM_PEDIDO (
    ID_Item INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_Pedido INT NOT NULL,
        FOREIGN KEY (ID_Pedido) REFERENCES PEDIDO(ID_Pedido),
    ID_Produto INT NOT NULL,
        FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto),
    Quantidade INT NOT NULL,
    Subtotal DECIMAL(7,2) NOT NULL
);
