CREATE DATABASE RPG;

USE RPG;

CREATE TABLE TABLE_STATUS (
    ID_STATUS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(15) NOT NULL
);

CREATE TABLE CONTA (
    ID_CONTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(30) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    ID_STATUS INT, FOREIGN KEY (ID_STATUS) REFERENCES TABLE_STATUS(ID_STATUS)
);

CREATE TABLE CLASSE (
    ID_CLASSE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL
);

CREATE TABLE RACA (
    ID_RACA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(120),
    XP_BASE INT NOT NULL,
    INTELIGENCIA_BASE INT NOT NULL,
    FORCA_BASE INT NOT NULL,
    AGILIDADE_BASE INT NOT NULL
);

CREATE TABLE PERSONAGEM (
    ID_PERSONAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    NIVEL INT NOT NULL DEFAULT 0,
    INTELIGENCIA INT NOT NULL,
    FORCA INT NOT NULL,
    AGILIDADE INT NOT NULL,
    ID_CLASSE INT, FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE(ID_CLASSE),
    ID_RACA INT, FOREIGN KEY (ID_RACA) REFERENCES RACA(ID_RACA),
    HP INT NOT NULL,
    XP INT NOT NULL,
    ID_CONTA INT, FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

CREATE TABLE TIPO_ITEM (
    ID_TIPO_ITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(15) NOT NULL
);

CREATE TABLE RARIDADES (
    ID_RARIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(10) NOT NULL,
    CHANCE_DROP INT NOT NULL
);

CREATE TABLE ITEM (
    ID_ITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    ID_TIPO_ITEM INT, FOREIGN KEY (ID_TIPO_ITEM) REFERENCES TIPO_ITEM(ID_TIPO_ITEM),
    DESCRICAO VARCHAR(120),
    ID_RACA INT, FOREIGN KEY (ID_RACA) REFERENCES RACA(ID_RACA),
    VALOR_COMPRA FLOAT NOT NULL,
    VALOR_VENDA FLOAT NOT NULL,
    NIVEL_REQUERIDO INT NOT NULL,
    ID_RARIDADE INT, FOREIGN KEY (ID_RARIDADE) REFERENCES RARIDADES(ID_RARIDADE),
    PONTOS_DANO INT NOT NULL,
    PONTOS_VIDA INT NOT NULL,
    PONTOS_INTELIGENCIA INT NOT NULL,
    PONTOS_FORCA INT NOT NULL,
    PONTOS_AGILIDADE INT NOT NULL,
);

CREATE TABLE INVENTARIO (
    ID_PERSONAGEM INT, FOREIGN KEY (ID_PERSONAGEM) REFERENCES PERSONAGEM(ID_PERSONAGEM),
    ID_ITEM INT, FOREIGN KEY (ID_ITEM) REFERENCES ITEM (ID_ITEM),
    QUANTIDADE INT NOT NULL
);

CREATE TABLE TIPO_PODER (
    ID_TIPO_PODER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(15) NOT NULL,
    DESCRICAO VARCHAR(120)
);

CREATE TABLE PODER (
    ID_PODER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    DESCRICAO VARCHAR(120),
    ID_TIPO_PODER INT, FOREIGN KEY (ID_TIPO_PODER) REFERENCES TIPO_PODER(ID_TIPO_PODER),
    PONTOS_ATAQUE INT NOT NULL,
    PONTOS_DEFESA INT NOT NULL,
    NIVEL_REQUERIDO INT NOT NULL
);