-- USE HAMBURGUERIA;

UPDATE FORNECEDOR
SET NOME = "Coca-Cola"
WHERE ID_Fornecedor = 1;

UPDATE FORNECEDOR
SET NOME = "Seara"
WHERE ID_Fornecedor = 2;

UPDATE FORNECEDOR
SET NOME = "JBS"
WHERE ID_Fornecedor = 3;

UPDATE FORNECEDOR
SET NOME = "Kibom"
WHERE ID_Fornecedor = 4;

UPDATE PRODUTO
SET PRECO = 9.00
WHERE NOME = "Batata Frita";

UPDATE FORMA_PAGAMENTO
SET TAXA = 3
WHERE ID_FORMA_PAGAMENTO = 2;